Repository kaplayjs/kaplay, pull requests merged in 2024-06, with the labels that each got.

#82 feat: All transforms needed to change the frame of reference from one place to another
  src/components/transform/pos.ts
  src/kaboom.ts
  src/types.ts
Labels: enhancement

#84 feat: Protect against invalid input
  examples/draw.js
  src/kaboom.ts
Labels: enhancement

#87 feat: Configurable radius for each corner of a rectangle
  examples/draw.js
  examples/rect.js
  src/kaboom.ts
  src/types.ts
Labels: enhancement

#107 feat: Square line cap
  examples/linecap.js
  src/kaboom.ts
Labels: enhancement

#119 feat: added higher order easing functions linear, steps and cubic-bezier
  CHANGELOG.md
  examples/easing.js
  src/kaboom.ts
  src/math.ts
  src/types.ts
Labels: enhancement

#121 feat: layers and layer component
  CHANGELOG.md
  examples/layers.js
  src/components/index.ts
  src/components/transform/layer.ts
  src/kaboom.ts
  src/types.ts
Labels: enhancement

#133 refactor: Removed trigonometric functions from get arc points
  src/kaboom.ts
Labels: Optimization

#134 chore: create PR template for new PRs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#136 feat: worldPos and screenPos can be used as setter now
  src/components/transform/pos.ts
Labels: feature

#137 feat: named component to assign a name, and query, a more versatile way to get certain objects
  examples/query.js
  src/components/index.ts
  src/components/misc/named.ts
  src/kaboom.ts
  src/types.ts
Labels: feature

#143 fix: triangulation
  examples/polygon.js
  src/components/draw/polygon.ts
  src/kaboom.ts
Labels: bug

#163 feat: faster tests
  .github/workflows/test.yml
  examples/ciTest.json
  scripts/test.js
Labels: CI

#175 feat: comps navigation mesh, sentry and patrol components, particle system, random from shape
  CHANGELOG.md
  examples/ghosthunting.js
  src/components/draw/particles.ts
  src/components/index.ts
  src/components/level/patrol.ts
  src/components/level/sentry.ts
  src/kaboom.ts
  src/math.ts
  src/math/navigation.ts
  src/math/navigationmesh.ts
  src/types.ts
Labels: feature

#183 feat: navigation and other components
  CHANGELOG.md
  CONTRIBUTING.md
  assets/sprites/particle_circle_filled.png
  assets/sprites/particle_circle_outline.png
  assets/sprites/particle_hexagon_filled.png
  assets/sprites/particle_star_filled.png
  examples/ghosthunting.js
  src/components/draw/particles.ts
  src/components/index.ts
  src/components/level/navigation.ts
  src/components/level/patrol.ts
  src/components/level/sentry.ts
  src/kaboom.ts
  src/math/navigation.ts
  src/math/navigationgrid.ts
  src/types.ts
Labels: feature
