Repository kaplayjs/kaplay, pull requests merged in 2024-05, with the labels that each got.

#37 feat: high level raycasting functions
  examples/mazeRaycastedLight.js
  examples/raycastObject.js
  examples/transformShape.js
  src/kaboom.ts
  src/math.ts
  src/types.ts
Labels: enhancement

#45 feat: support for textured polygons
  CHANGELOG.md
  examples/polygonuv.js
  src/kaboom.ts
  src/types.ts
Labels: enhancement

#47 feat: Support for triangulation and concave polygon drawing
  CHANGELOG.md
  examples/polygon.js
  src/kaboom.ts
  src/math.ts
  src/types.ts
Labels: enhancement

#50 fix: Fixes horizontal velocity when on platform
  src/kaboom.ts
Labels: bug

#54 refactor: internal `getKaboomCtx` and `getInternalCtx`, modulizate components
  examples/multiboom.js
  src/components/draw/circle.ts
  src/components/draw/drawon.ts
  src/components/draw/fadeIn.ts
  src/components/draw/mask.ts
  src/components/draw/opacity.ts
  src/components/draw/outline.ts
  src/components/draw/polygon.ts
  src/components/draw/raycast.ts
  src/components/draw/rect.ts
  src/components/draw/shader.ts
  src/components/draw/sprite.ts
  src/components/draw/text.ts
  src/components/draw/uvquad.ts
  src/components/index.ts
  src/components/level/agent.ts
  src/components/level/tile.ts
  src/components/misc/health.ts
  src/components/misc/lifespan.ts
  src/components/misc/state.ts
  src/components/misc/stay.ts
  src/components/misc/timer.ts
  src/components/physics/area.ts
  src/components/physics/body.ts
  src/components/physics/doubleJump.ts
  src/components/transform/anchor.ts
  src/components/transform/fixed.ts
  src/components/transform/follow.ts
  src/components/transform/move.ts
  src/components/transform/offscreen.ts
  src/components/transform/pos.ts
  src/components/transform/rotate.ts
  src/components/transform/scale.ts
  src/components/transform/z.ts
  src/kaboom.ts
  src/types.ts
  tsconfig.json
Labels: refactor

#60 feat: Gravity direction
  CHANGELOG.md
  src/components/physics/body.ts
  src/kaboom.ts
  src/types.ts
Labels: enhancement

#66 fix: Fixes 0 gravity
  src/components/physics/body.ts
  src/kaboom.ts
Labels: bug

#71 feat: Adds opacity and line join option to outline
  examples/linejoin.js
  src/components/draw/outline.ts
  src/kaboom.ts
  src/types.ts
Labels: enhancement
