Repository kaplayjs/kaplay, pull requests merged in 2024-08, with the labels that each got.

#296 fix: Fixes ellipse to matrix
  src/math/math.ts
Labels: feature

#303 fix: platform jitter
  src/components/physics/body.ts
Labels: feature

#306 fix: Fixes cutting the polygon during buoyancy calculation
  src/components/physics/effectors.ts
  src/math/math.ts
Labels: feature

#314 feature: only do collision check when needed
  src/components/physics/area.ts
  src/kaplay.ts
Labels: feature

#313 feat: Interpolate between this and next physics frame
  src/app/app.ts
  src/app/frame.ts
  src/components/physics/body.ts
  src/kaplay.ts
  src/types.ts
Labels: feature

#321 feat: Interpolate between this and next physics frame
  src/app/app.ts
  src/app/frame.ts
  src/components/physics/body.ts
  src/kaplay.ts
  src/types.ts
Labels: feature

#329 fix: Normal did not have length 1, Level raycast was bugged
  examples/raycastLevelTest.js
  src/game/level.ts
  src/math/math.ts
Labels: feature

#327 fix: Normal did not have length 1
  examples/raycastLevelTest.js
  src/game/level.ts
  src/math/math.ts
Labels: feature

#346 fix: Makes sure an area has body before applying forces
  src/components/physics/effectors.ts
Labels: feature

#345 feat: Fixes mixed physics & manual changes
  src/components/physics/body.ts
Labels: feature

#342 fix: Only apply forces to bodies
  src/components/physics/effectors.ts
Labels: feature

#341 feat: Fixes mixed physics & manual changes
  src/components/physics/body.ts
Labels: feature

#352 fix: text cropped
  src/gfx/formatText.ts
Labels: need-dup

#354 fix: text cropped
  src/gfx/formatText.ts
Labels: need-dup

#356 fix: text cropped
  src/gfx/formatText.ts
Labels: need-dup

#364 Fixes fallOff and ground logic
  src/components/physics/area.ts
  src/components/physics/body.ts
  src/kaplay.ts
Labels: feature

#363 Fixes fallOff and ground logic
  src/components/physics/area.ts
  src/components/physics/body.ts
  src/kaplay.ts
Labels: feature

#362 doc: add notice to stay() component
  src/types.ts
Labels: v3001&v4000

#366 feat: return gamepad on gamepad events
  CHANGELOG.md
  src/app/app.ts
  src/index.ts
  src/types.ts
Labels: v3001&v4000

#370 feat: add keyboardCode on input bindings
  CHANGELOG.md
  src/app/app.ts
  src/app/inputBindings.ts
Labels: v3001&v4000

#375 Makes onFixedUpdate attach to fixedUpdate
  examples/fixedUpdate.js
  src/game/events/events.ts
Labels: feature

#374 feat: Makes onFixedUpdate attach to fixedUpdate
  examples/fixedUpdate.js
  src/game/events/events.ts
Labels: feature
