Repository kaplayjs/kaplay, pull requests merged in 2024-10, with the labels that each got.

#423 feat: Always clear velocity
  src/components/physics/body.ts
Labels: feature

#431 feat: Adds restitution and friction
  CHANGELOG.md
  examples/friction.js
  examples/restitution.js
  src/components/physics/area.ts
  src/components/physics/body.ts
Labels: feature

#432 feat(types): remove backwards compat of types also export remaining types on index.ts
  README.md
  src/game/make.ts
  src/index.ts
  src/types.ts
Labels: types

#456 feat: Replaces the broad phase collision detection, introduces a new renderer and has numerous optimizations
  examples/bench.js
  src/components/draw/particles.ts
  src/components/physics/area.ts
  src/components/physics/body.ts
  src/components/transform/pos.ts
  src/game/camera.ts
  src/game/game.ts
  src/game/level.ts
  src/game/make.ts
  src/game/scenes.ts
  src/gfx/anchor.ts
  src/gfx/draw/drawDebug.ts
  src/gfx/draw/drawFormattedText.ts
  src/gfx/draw/drawFrame.ts
  src/gfx/draw/drawInspectText.ts
  src/gfx/draw/drawLine.ts
  src/gfx/draw/drawPolygon.ts
  src/gfx/draw/drawRaw.ts
  src/gfx/draw/drawTexture.ts
  src/gfx/draw/drawUVQuad.ts
  src/gfx/gfx.ts
  src/gfx/gfxApp.ts
  src/gfx/stack.ts
  src/kaplay.ts
  src/math/index.ts
  src/math/math.ts
  src/math/spatial/hashgrid.ts
  src/math/spatial/sweepandprune.ts
  src/math/various.ts
  src/types.ts
Labels: enhancement

#457 docs: fix spelling mistakes in jsdoc (+ a bit of formatting)
  src/types.ts
Labels: v3001&v4000

#467 fix: Use line color if set
  src/gfx/draw/drawLine.ts
Labels: enhancement

#470 fix color components
  src/gfx/draw/drawLine.ts
Labels: enhancement

#480 feat: Added clipLineToRect
  CHANGELOG.md
  examples/clip.js
  src/kaplay.ts
  src/math/math.ts
  src/types.ts
Labels: enhancement
