Repository kaplayjs/kaplay, pull requests merged in 2025-05, with the labels that each got.

#766 Add SAT as option
  examples/platformer.js
  src/ecs/systems/collision.ts
  src/kaplay.ts
  src/math/sat.ts
  src/types.ts
Labels: enhancement

#771 chore: Help Menu
  help.json
  package.json
  pnpm-lock.yaml
Labels: chore

#784 feat: Cache matrix inverse, transform point in hasPoint instead of transforming area
  src/ecs/components/physics/area.ts
  src/math/math.ts
Labels: performance

#785 feat: Added opacities to drawPolygon to specify per vertex opacity
  src/ecs/components/draw/polygon.ts
  src/gfx/draw/drawPolygon.ts
  src/types.ts
  tests/playtests/polygonuv.js
Labels: enhancement
