Repository kaplayjs/kaplay, pull requests merged in 2025-01, with the labels that each got.

#579 feat: strict .use()
  CHANGELOG.md
  src/components/draw/text.ts
  src/game/make.ts
  src/gfx/draw/drawText.ts
  src/gfx/formatText.ts
  tests/playtests/styleOverride.js
  tests/playtests/textwrap.js
Labels: crossplay

#583 fix: Fixed shader to apply alpha correctly
  src/constants.ts
Labels: enhancement

#592 feat: css colors
  .vscode/snippets.code-snippets
  CHANGELOG.md
  CONTRIBUTING.md
  examples/lifespan.js
  examples/particle.js
  src/assets/bitmapFont.ts
  src/assets/sprite.ts
  src/kaplay.ts
  src/kassets/happy.png
  src/math/color.ts
  src/types.ts
  tests/playtests/css_color.js
Labels: cherry-pick, changelog
