Repository kaplayjs/kaplay, pull requests merged in 2025-03, with the labels that each got.

#619 feat: Slice game
  examples/slice.js
  src/math/math.ts
Labels: enhancement

#612 docs: add jsdoc to shader, area and follow properties
  src/components/draw/shader.ts
  src/components/physics/area.ts
  src/components/transform/follow.ts
Labels: cherry-pick, changelog

#624 fix: debug.timeScale wasn't affecting dt()
  .vscode/settings.json
  examples/blend.js
  examples/slice.js
  src/app/frame.ts
  src/app/index.ts
  src/assets/shader.ts
  src/components/draw/fadeIn.ts
  src/components/draw/particles.ts
  src/components/draw/sprite.ts
  src/components/index.ts
  src/components/level/sentry.ts
  src/components/misc/animate.ts
  src/components/misc/boom.ts
  src/components/physics/body.ts
  src/components/physics/effectors.ts
  src/components/transform/pos.ts
  src/constants.ts
  src/events/globalEvents.ts
  src/game/make.ts
  src/gfx/draw/drawFrame.ts
  src/gfx/draw/drawRaw.ts
  src/gfx/gfx.ts
  src/kaplay.ts
  src/math/gjk.ts
  src/math/math.ts
  tests/playtests/debug_timeScale.js
Labels: cherry-pick, changelog

#629 fix: wrong calculation in vector dot
  src/math/math.ts
  src/math/vec3.ts
Labels: cherry-pick, changelog

#640 doc: Add clarification to loadAseprite
  src/types.ts
Labels: cherry-pick

#641 fix: catch errors for missing dependencies in object creation
  src/game/make.ts
  src/kaplay.ts
  src/types.ts
  tests/playtests/missing_comps.js
  tests/playtests/missing_comps_dynamic.js
Labels: cherry-pick, changelog

#652 drawCanvas
  CHANGELOG.md
  src/gfx/draw/drawCanvas.ts
  src/gfx/draw/index.ts
  src/index.ts
  src/kaplay.ts
  src/types.ts
Labels: enhancement

#651 feat: Video component
  CHANGELOG.md
  examples/video.js
  src/components/draw/index.ts
  src/components/draw/video.ts
  src/kaplay.ts
  src/types.ts
Labels: enhancement

#653 feat: Video size for area, picture component
  src/components/draw/index.ts
  src/components/draw/picture.ts
  src/components/draw/video.ts
  src/kaplay.ts
  src/types.ts
Labels: enhancement

#658 fix: Fixes issues in 9slice (anchor and empty center)
  examples/slice9.js
  src/components/draw/sprite.ts
Labels: enhancement

#657 fix: Fixes outline on circles
  examples/draw.js
  examples/linejoin.js
  src/gfx/draw/drawPolygon.ts
  src/math/various.ts
Labels: enhancement, cherry-pick, changelog

#662 feat: tuple component list
  CHANGELOG.md
  src/game/make.ts
  src/types.ts
  tests/types/GameObj.test-d.ts
Labels: types

#679 Picture as render target, drawon can now be used for caching child draw
  examples/drawon.js
  src/components/draw/drawon.ts
  src/ecs/make.ts
  src/gfx/draw/drawPicture.ts
  src/gfx/stack.ts
  src/types.ts
Labels: enhancement
